# Generated by Django 5.0.6 on 2024-06-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OreLuce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora_alba', models.TimeField()),
                ('ora_tramonto', models.TimeField()),
                ('ora_legale', models.BooleanField()),
            ],
        ),
    ]
