# Generated by Django 5.0.6 on 2024-06-05 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suono',
            name='data',
            field=models.DateField(default=datetime.date(1990, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suono',
            name='ora',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
