# Generated by Django 5.0.6 on 2024-06-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suono', '0002_suono_data_suono_ora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suono',
            name='data_e_ora',
        ),
    ]
